export const BASELINE_COMPARISON_ACTIONS = {
  SAVE_BASELINE: "SAVE_BASELINE",
  SAVE_COMPARISON: "SAVE_COMPARISON",
  RETRIEVE_CONTEXT: "RETRIEVE_CONTEXT",
  CLEAR_CONTEXT: "CLEAR_CONTEXT",
} as const;

export const FORGET_CLASS_ACTIONS = {
  SAVE_FORGET_CLASS: "SAVE_FORGET_CLASS",
  ADD_SELECTED_FORGET_CLASS: "ADD_SELECTED_FORGET_CLASS",
  RETRIEVE_FORGET_CLASS_CONTEXT_DATA: "RETRIEVE_FORGET_CLASS_CONTEXT_DATA",
  CLEAR_FORGET_CLASS: "CLEAR_FORGET_CLASS",
  DELETE_SELECTED_FORGET_CLASS: "DELETE_SELECTED_FORGET_CLASS",
} as const;

export const EXPERIMENTS_ACTIONS = {
  ADD_EXPERIMENT: "ADD_EXPERIMENT",
  UPDATE_EXPERIMENT: "UPDATE_EXPERIMENT",
  SAVE_EXPERIMENTS: "SAVE_EXPERIMENTS",
  RETRIEVE_EXPERIMENTS: "RETRIEVE_EXPERIMENTS",
  DELETE_EXPERIMENT: "DELETE_EXPERIMENT",
  SET_IS_EXPERIMENTS_LOADING: "SET_IS_EXPERIMENTS_LOADING",
} as const;

export const RUNNING_STATUS_ACTIONS = {
  UPDATE_IS_RUNNING: "UPDATE_IS_RUNNING",
  INIT_STATUS: "INIT_STATUS",
  RETRIEVE_STATUS: "RETRIEVE_STATUS",
  UPDATE_STATUS: "UPDATE_STATUS",
  UPDATE_ACTIVE_STEP: "UPDATE_ACTIVE_STEP",
} as const;

export const DATASET_AND_MODEL_ACTIONS = {
  SAVE_DATASET: "SAVE_DATASET",
  SAVE_NEURAL_NETWORK_MODEL: "SAVE_NEURAL_NETWORK_MODEL",
  RETRIEVE_DATASET_AND_MODEL: "RETRIEVE_DATASET_AND_MODEL",
} as const;

export const RUNNING_INDEX_ACTIONS = {
  UPDATE_RUNNING_INDEX: "UPDATE_RUNNING_INDEX",
  RETRIEVE_RUNNING_INDEX: "RETRIEVE_RUNNING_INDEX",
} as const;
