export const APP_WIDTH = 1805;
export const CORE_WIDTH = 1312;
export const EXPERIMENTS_WIDTH = 1032;
export const ANALYSIS_VIEW_WIDTH = 493;
export const PROGRESS_WIDTH = CORE_WIDTH - EXPERIMENTS_WIDTH;

export const CORE_HEIGHT = 677;
export const EXPERIMENTS_PROGRESS_HEIGHT = 234;
export const ACCURACIES_HEIGHT = 293;
export const PREDICTIONS_HEIGHT = 316;
export const CORRELATIONS_HEIGHT =
  EXPERIMENTS_PROGRESS_HEIGHT +
  CORE_HEIGHT -
  ACCURACIES_HEIGHT -
  PREDICTIONS_HEIGHT;
